celebrities = [
    {"name": "Instagram", "followers": 689, "country": "–",
        "profession": "Social media platform"},
    {"name": "Cristiano Ronaldo", "followers": 654,
        "country": "Portugal", "profession": "Footballer"},
    {"name": "Lionel Messi", "followers": 505,
        "country": "Argentina", "profession": "Footballer"},
    {"name": "Selena Gomez", "followers": 420,
        "country": "USA", "profession": "Musician & actress"},
    {"name": "Dwayne Johnson", "followers": 393,
        "country": "USA", "profession": "Actor & wrestler"},
    {"name": "Kylie Jenner", "followers": 393,
        "country": "USA", "profession": "Media personality"},
    {"name": "Ariana Grande", "followers": 375,
        "country": "USA", "profession": "Musician & actress"},
    {"name": "Kim Kardashian", "followers": 356,
        "country": "USA", "profession": "Media personality"},
    {"name": "Beyoncé", "followers": 311, "country": "USA",
        "profession": "Musician & actress"},
    {"name": "Khloé Kardashian", "followers": 302,
        "country": "USA", "profession": "Media personality"},
    {"name": "Nike", "followers": 300, "country": "USA",
        "profession": "Sportswear brand"},
    {"name": "Justin Bieber", "followers": 294,
        "country": "Canada", "profession": "Musician"},
    {"name": "Kendall Jenner", "followers": 287,
        "country": "USA", "profession": "Media personality"},
    {"name": "Taylor Swift", "followers": 281,
        "country": "USA", "profession": "Musician"},
    {"name": "National Geographic", "followers": 278,
        "country": "USA", "profession": "Magazine"},
    {"name": "Virat Kohli", "followers": 272,
        "country": "India", "profession": "Cricketer"},
    {"name": "Jennifer Lopez", "followers": 249,
        "country": "USA", "profession": "Musician & actress"},
    {"name": "Neymar Jr.", "followers": 229,
        "country": "Brazil", "profession": "Footballer"},
    {"name": "Nicki Minaj", "followers": 225,
        "country": "USA", "profession": "Musician"},
    {"name": "Kourtney Kardashian", "followers": 218,
        "country": "USA", "profession": "Media personality"},
    {"name": "Miley Cyrus", "followers": 212,
        "country": "USA", "profession": "Musician & actress"},
    {"name": "Katy Perry", "followers": 204,
        "country": "USA", "profession": "Musician"},
    {"name": "Zendaya", "followers": 178, "country": "USA",
        "profession": "Actress & singer"},
    {"name": "Kevin Hart", "followers": 177,
        "country": "USA", "profession": "Comedian & actor"},
    {"name": "Real Madrid CF", "followers": 175,
        "country": "Spain", "profession": "Football club"},
    {"name": "Cardi B", "followers": 164, "country": "USA",
        "profession": "Musician & actress"},
    {"name": "LeBron James", "followers": 159,
        "country": "USA", "profession": "Basketball player"},
    {"name": "Demi Lovato", "followers": 153,
        "country": "USA", "profession": "Musician & actress"},
    {"name": "Rihanna", "followers": 149,
        "country": "Barbados", "profession": "Musician"},
    {"name": "Chris Brown", "followers": 144,
        "country": "USA", "profession": "Musician"},
    {"name": "Drake", "followers": 142, "country": "Canada", "profession": "Musician"},
    {"name": "FC Barcelona", "followers": 141,
        "country": "Spain", "profession": "Football club"},
    {"name": "Ellen DeGeneres", "followers": 136,
        "country": "USA", "profession": "Comedian & host"},
    {"name": "Billie Eilish", "followers": 124,
        "country": "USA", "profession": "Musician"},
    {"name": "Kylian Mbappé", "followers": 124,
        "country": "France", "profession": "Footballer"},
    {"name": "UEFA Champions League", "followers": 121,
        "country": "Europe", "profession": "Football competition"},
    {"name": "Gal Gadot", "followers": 108,
        "country": "Israel", "profession": "Actress"},
    {"name": "Lisa", "followers": 106,
        "country": "Thailand", "profession": "Musician"},
    {"name": "Vin Diesel", "followers": 103,
        "country": "USA", "profession": "Actor"},
    {"name": "NASA", "followers": 96.4,
        "country": "USA", "profession": "Space agency"},
    {"name": "Shraddha Kapoor", "followers": 94.2,
        "country": "India", "profession": "Actress"},
    {"name": "Narendra Modi", "followers": 95.8,
        "country": "India", "profession": "Prime Minister"},
    {"name": "Priyanka Chopra", "followers": 92.4,
        "country": "India", "profession": "Actress"},
    {"name": "Shakira", "followers": 92.4,
        "country": "Colombia", "profession": "Musician"},
    {"name": "NBA", "followers": 90.7, "country": "USA",
        "profession": "Basketball league"},
    {"name": "Snoop Dogg", "followers": 88.4,
        "country": "USA", "profession": "Musician"},
    {"name": "David Beckham", "followers": 88.1,
        "country": "UK", "profession": "Former footballer"},
    {"name": "Dua Lipa", "followers": 87.4,
        "country": "UK", "profession": "Musician"},
    {"name": "Jennie", "followers": 87.1,
        "country": "South Korea", "profession": "Musician"},
    {"name": "Alia Bhatt", "followers": 86.3,
        "country": "India", "profession": "Actress"}
]
